# Generated by Django 4.2.6 on 2023-11-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileencryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='key_file',
            field=models.FileField(default=b'', upload_to='keys/'),
        ),
    ]
