# Generated by Django 4.2.6 on 2023-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileencryption', '0002_add_default_to_key_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='keys/')),
                ('key_file', models.FileField(upload_to='keys/')),
            ],
        ),
    ]
